# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Blog' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.0.4'
pod 'YYModel'
pod 'MaterialControls', '~> 1.1.0'
pod 'SDWebImage', '~>3.7'
pod 'MJRefresh'
pod 'Masonry'
pod 'BLKFlexibleHeightBar'
  # Pods for Blog

  target 'BlogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
